language: java
jdk: openjdk8
branches:
  only:
  - master
  - "/.*-[0-9]+\\..*/"
install: true
script: ".travis/build.sh"
env:
  global:
  - secure: qfvEv5biI6CnXHQp9Nap+gPQxkcatNjVJmNK5L4g5t4TyeAkbawgZTSCXi/c602MRp/zc7VGfua6d5bL1yqb3d5Xnzqs8ZJnnDzouTd+p393ocXDoiByMyrfrV54AJka7VCcbgiCwFzIDIoifsVodB1jeLGYUqECRiqCCrMXhwQ=
  - secure: HszAbBUV3GyT064LyhT0Kn4ktVBgwjuWV3EUwHekUnIg9Xn51U5lJUeQj+5u5/BWFMRCOEDTDqbcmDwSCt6voGuzK8BddyDDbvWrYuhwzaYJIeqW03SGzERme1d2XvI72eOpTVtQc8GAmEjg8hm713oc8+bFIkieKtYvICo0xt4=
